# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.cache/wt [current_project]
set_property parent.project_path D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/sources_1/new/Reg_File.v
  D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/sources_1/new/Mem_Ins.v
  D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/sources_1/new/Mem_Data.v
  D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/sources_1/new/Controller.v
  D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/sources_1/new/Alu.v
  D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/sources_1/new/DividerShow.v
  D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/sources_1/new/Datapath.v
  D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/sources_1/new/Divider.v
  D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/sources_1/new/Button_Signal.v
  D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/sources_1/new/Number2Seg.v
  D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/sources_1/new/FindData.v
  D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/sources_1/new/CPU.v
  D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/sources_1/new/View.v
}
read_xdc D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/constrs_1/new/cstr.xdc
set_property used_in_implementation false [get_files D:/ARCHIVE/VIVADO_WORKPLACE/CPU/CPU.srcs/constrs_1/new/cstr.xdc]

synth_design -top View -part xc7a100tcsg324-1
write_checkpoint -noxdef View.dcp
catch { report_utilization -file View_utilization_synth.rpt -pb View_utilization_synth.pb }
